// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-Cnv9seQYG3EqGl79qI7RQBZ-ng2sPw',
    appId: '1:294161974265:web:8e51d7575d3acc588db328',
    messagingSenderId: '294161974265',
    projectId: 'fir-iot-e5b03',
    authDomain: 'fir-iot-e5b03.firebaseapp.com',
    databaseURL: 'https://fir-iot-e5b03-default-rtdb.firebaseio.com',
    storageBucket: 'fir-iot-e5b03.appspot.com',
    measurementId: 'G-BZFGNN41BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAoWoe0K9opoXYZsNw9-CEapWLnEEiJKE',
    appId: '1:294161974265:android:d6378f0ea6be2a9a8db328',
    messagingSenderId: '294161974265',
    projectId: 'fir-iot-e5b03',
    databaseURL: 'https://fir-iot-e5b03-default-rtdb.firebaseio.com',
    storageBucket: 'fir-iot-e5b03.appspot.com',
  );
}
